services:
  app:
    image: railway/python:3.9
    command: |
      . venv/bin/activate
      gunicorn app:app --workers 1 --worker-class gthread --threads 4 --log-level info
    env:
      PYTHONUNBUFFERED: 1
      PORT: $${PORT}
    http:
      /:
        get:
          command: python -m flask run